// RFC 6887 PCP wire codec: v2 common header, MAP opcode payload and the
// PREFER_FAILURE option. Only the v1 AntiNAT subset is encoded; decoding
// rejects wrong versions/opcodes, bad lengths and malformed echoes instead
// of guessing.
package pcp

import (
	"encoding/binary"
	"errors"
	"fmt"
	"math"
	"net/netip"
	"time"
)

// PCP v2 constants (RFC 6887).
const (
	// Version is the PCP protocol version this client speaks.
	Version byte = 2

	// HeaderSize is the 24-byte PCP common header:
	// request = version/opcode/reserved (4) + lifetime (4) + client IP (16);
	// response = version/opcode/reserved/result (4) + lifetime (4) +
	// epoch (4) + reserved (12).
	HeaderSize = 24
	// MapPayloadSize is the 36-byte MAP opcode payload.
	MapPayloadSize = 36

	// OpCodeAnnounce is the side-effect-free discovery opcode (§8.4).
	OpCodeAnnounce byte = 0
	// OpCodeMap is the MAP opcode (§11).
	OpCodeMap byte = 1

	RequestFlag  byte = 0x00
	ResponseFlag byte = 0x80

	ProtoTCP byte = 6
	ProtoUDP byte = 17

	// PCP option headers are code(1), reserved(1), length(2).
	OptionPreferFailure byte = 2

	DefaultServerPort uint16 = 5351
)

// Base result codes (RFC 6887 §7.4). Codes 14..31 are further permanent
// failures and codes >= 128 are transient failures.
const (
	ResultSuccess               byte = 0
	ResultUnsupportedVersion    byte = 1
	ResultNotAuthorized         byte = 2
	ResultMalformedRequest      byte = 3
	ResultUnsupportedOpcode     byte = 4
	ResultUnsupportedOption     byte = 5
	ResultMalformedOption       byte = 6
	ResultNetworkFailure        byte = 7
	ResultNoResources           byte = 8
	ResultUnsupportedProtocol   byte = 9
	ResultUserExQuota           byte = 10
	ResultCannotProvideExternal byte = 11
	ResultAddressMismatch       byte = 12
	ResultExcessiveRemotePeers  byte = 13
)

func TransientResult(code byte) bool { return code >= 128 }

var (
	ErrTruncated     = errors.New("pcp: response truncated")
	ErrWrongVersion  = errors.New("pcp: response version mismatch")
	ErrWrongOpcode   = errors.New("pcp: response opcode mismatch")
	ErrTrailingBytes = errors.New("pcp: unexpected response length")
	ErrInternalPort  = errors.New("pcp: internal port mismatch in response")
	ErrProtocol      = errors.New("pcp: protocol mismatch in response")
	ErrBadMappedAddr = errors.New("pcp: assigned external address is not IPv4")
)

func putUint32(b []byte, v uint32) { binary.BigEndian.PutUint32(b, v) }
func putUint16(b []byte, v uint16) { binary.BigEndian.PutUint16(b, v) }
func readUint32(b []byte) uint32   { return binary.BigEndian.Uint32(b) }
func readUint16(b []byte) uint16   { return binary.BigEndian.Uint16(b) }

// v4Mapped encodes IPv4 into the 128-bit IPv4-mapped form PCP carries in
// request headers and MAP payloads.
func v4Mapped(addr netip.Addr) []byte {
	b := make([]byte, 16)
	if addr.Is4() {
		b[10], b[11] = 0xff, 0xff
		a4 := addr.As4()
		copy(b[12:16], a4[:])
	}
	return b
}

// mappedToV4 decodes a 128-bit external-address field. RFC-compliant
// IPv4-mapped form is preferred; the all-zero wildcard and IPv4-compatible
// form emitted by miniupnpd are accepted conservatively. A zero result is an
// unknown first-hop address, never a public candidate.
func mappedToV4(b []byte) (netip.Addr, error) {
	if len(b) != 16 {
		return netip.Addr{}, fmt.Errorf("%w: field is %d bytes", ErrBadMappedAddr, len(b))
	}
	if b[10] == 0xff && b[11] == 0xff {
		return netip.AddrFrom4([4]byte(b[12:16])), nil
	}
	topZero := true
	for _, v := range b[:12] {
		if v != 0 {
			topZero = false
			break
		}
	}
	if topZero {
		return netip.AddrFrom4([4]byte(b[12:16])), nil
	}
	return netip.Addr{}, ErrBadMappedAddr
}

// buildMapRequest encodes one MAP request: 24-byte common request header,
// 36-byte MAP payload, and PREFER_FAILURE when exact port is required. The
// nonce must already be generated by the caller (strong ownership state).
func buildMapRequest(req MapRequest, nonce [12]byte) ([]byte, error) {
	if req.Protocol != ProtoTCP && req.Protocol != ProtoUDP {
		return nil, fmt.Errorf("pcp: unsupported MAP protocol %d", req.Protocol)
	}
	if req.PreferFailure && req.SuggestedExternalPort == 0 {
		return nil, ErrPreferFailureRequiresPort
	}
	if !req.InternalAddress.IsValid() || !req.InternalAddress.Is4() {
		return nil, fmt.Errorf("pcp: MAP requires a concrete IPv4 internal address, got %v", req.InternalAddress)
	}
	if req.Lifetime < 0 || uint64(req.Lifetime/time.Second) > math.MaxUint32 {
		return nil, fmt.Errorf("pcp: lifetime %s is outside uint32 seconds", req.Lifetime)
	}

	packet := make([]byte, HeaderSize+MapPayloadSize)
	packet[0] = Version
	packet[1] = RequestFlag | OpCodeMap
	putUint32(packet[4:8], uint32(req.Lifetime/time.Second))
	copy(packet[8:24], v4Mapped(req.InternalAddress))

	payload := packet[HeaderSize:]
	copy(payload[0:12], nonce[:])
	payload[12] = req.Protocol
	putUint16(payload[16:18], req.InternalPort)
	putUint16(payload[18:20], req.SuggestedExternalPort)
	// payload[20:36] suggested external IP remains wildcard zero in v1.

	if req.PreferFailure {
		packet = append(packet, OptionPreferFailure, 0, 0, 0)
	}
	return packet, nil
}

func buildAnnounceRequest(clientAddr netip.Addr) ([]byte, error) {
	if !clientAddr.IsValid() || !clientAddr.Is4() {
		return nil, fmt.Errorf("pcp: ANNOUNCE requires a concrete IPv4 client address, got %v", clientAddr)
	}
	packet := make([]byte, HeaderSize)
	packet[0] = Version
	packet[1] = RequestFlag | OpCodeAnnounce
	copy(packet[8:24], v4Mapped(clientAddr))
	return packet, nil
}

// mapResponse is the decoded common response plus MAP payload.
type mapResponse struct {
	ResultCode              byte
	LifetimeSeconds         uint32
	Epoch                   uint32
	Nonce                   [12]byte
	Protocol                byte
	InternalPort            uint16
	AssignedExternalPort    uint16
	AssignedExternalAddress netip.Addr
}

// parseAnnounceResponse decodes the exact 24-byte common response header.
func parseAnnounceResponse(packet []byte) (mapResponse, error) {
	var zero mapResponse
	if len(packet) < HeaderSize {
		return zero, fmt.Errorf("%w: %d bytes", ErrTruncated, len(packet))
	}
	if len(packet) != HeaderSize {
		return zero, fmt.Errorf("%w: got %d bytes, want %d", ErrTrailingBytes, len(packet), HeaderSize)
	}
	if packet[0] != Version {
		return zero, fmt.Errorf("%w: got %d", ErrWrongVersion, packet[0])
	}
	if packet[1] != ResponseFlag|OpCodeAnnounce {
		return zero, fmt.Errorf("%w: got %02x", ErrWrongOpcode, packet[1])
	}
	return mapResponse{
		ResultCode:      packet[3],
		LifetimeSeconds: readUint32(packet[4:8]),
		Epoch:           readUint32(packet[8:12]),
	}, nil
}

// parseMapResponse decodes a MAP response. Successful responses are the
// exact 60-byte form and the nonce echo is the strong ownership proof.
// Error responses may be header-only or echo the whole request — including
// its options (RFC 6887 §8.2) — so any 4-byte-aligned length of at least
// the header is accepted and only the header is classified.
func parseMapResponse(packet []byte, wantProtocol byte, wantInternalPort uint16) (mapResponse, error) {
	var zero mapResponse
	if len(packet) < HeaderSize {
		return zero, fmt.Errorf("%w: %d bytes", ErrTruncated, len(packet))
	}
	if len(packet)%4 != 0 {
		return zero, fmt.Errorf("%w: %d bytes is not 4-byte aligned", ErrTrailingBytes, len(packet))
	}
	if packet[0] != Version {
		return zero, fmt.Errorf("%w: got %d", ErrWrongVersion, packet[0])
	}
	if packet[1] != ResponseFlag|OpCodeMap {
		return zero, fmt.Errorf("%w: got %02x", ErrWrongOpcode, packet[1])
	}
	response := mapResponse{
		ResultCode:      packet[3],
		LifetimeSeconds: readUint32(packet[4:8]),
		Epoch:           readUint32(packet[8:12]),
	}
	if response.ResultCode != ResultSuccess {
		// The echoed request payload carries no ownership proof: classify
		// the result code and stop.
		return response, nil
	}
	if len(packet) != HeaderSize+MapPayloadSize {
		return zero, fmt.Errorf("%w: got %d bytes, want %d", ErrTrailingBytes, len(packet), HeaderSize+MapPayloadSize)
	}
	payload := packet[HeaderSize:]
	copy(response.Nonce[:], payload[0:12])
	response.Protocol = payload[12]
	response.InternalPort = readUint16(payload[16:18])
	response.AssignedExternalPort = readUint16(payload[18:20])
	external, err := mappedToV4(payload[20:36])
	if err != nil {
		return zero, err
	}
	response.AssignedExternalAddress = external
	if response.Protocol != wantProtocol {
		return zero, fmt.Errorf("%w: got %d want %d", ErrProtocol, response.Protocol, wantProtocol)
	}
	if response.InternalPort != wantInternalPort {
		return zero, fmt.Errorf("%w: got %d want %d", ErrInternalPort, response.InternalPort, wantInternalPort)
	}
	return response, nil
}
